### ISSUE TITLE
clear button hidden when edit text box is empty

### ISSUE THREAD

**Issue by sd6352051** [rengwuxian/MaterialEditText#154] opened 2015-03-31 05:52 UTC
hi Zhu Kai 

I want remove clear button when edit text box is empty.Thanks

**Comment by rengwuxian** [comment] 2015-03-31 07:00
This feature is coming soon.

**Comment by sd6352051** [comment] 2015-04-02 08:28
What time release the next version,I really like this feature.But I don't want this button show when edit text box is empty.Thanks:)

**Comment by rengwuxian** [comment] 2015-04-26 16:20
Hi @sd6352051 ,

sorry for the delayed reply.

I'm considering to hide clear button for now, because it looks useless. So let's not worry about the solution about the "close button" (I don't think it's a good name^_^) now.

This change will be in the next version, within a few HOURS.

**Comment by sd6352051** [comment] 2015-04-27 01:57
No Worries, You are the man ;)

**Comment by rengwuxian** [comment] 2015-04-29 00:34
Hi @sd6352051 ,

Thanks for your words.

2.1.3 has been released, with the "close button" (not clear button) removed.

You can check the [latest library version](https://github.com/rengwuxian/MaterialEditText#download) now.

**Comment by sd6352051** [comment] 2015-04-29 11:15
worked perfect. :smile:  but i think  [this code][1] shouldn't write here,

you can wrote in README such as
gradle:
```groovy
compile 'com.rengwuxian.materialedittext:library:2.1.3'
compile 'com.android.support:support-annotations:22.0.0'
compile 'com.nineoldandroids:library:2.4.0'
compile 'com.android.support:appcompat-v7:22.1.0'
```

[1]: https://github.com/rengwuxian/MaterialEditText/blob/master/library/build.gradle#L20-L22

**Comment by rengwuxian** [comment] 2015-06-04 03:24
MaterialEditText 2.x has switched to depend on `appcompat-v7`'s `AppCompat` widgets, such as `AppCompatEditText`. So I have to add this dependency into the build script.

**Comment by rengwuxian** [comment] 2015-06-04 03:24
Close as the issue is resolved.

**Closed by rengwuxian** 2015-06-04 03:24 UTC
Labels: enhancement
