### ISSUE TITLE
java.lang.IllegalArgumentException: Layout: -64 < 0

### ISSUE THREAD

**Issue by pawelantczak** [rengwuxian/MaterialEditText#75] opened 2015-01-15 13:41 UTC
Hello.
Error appears in In use case like this:
```xml
    <com.rengwuxian.materialedittext.MaterialEditText
        android:id="@+id/number"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:hint="Numer paczki"
        android:paddingBottom="16dp"
        android:textSize="@dimen/add_screen_font_size"
        app:baseColor="?android:textColorSecondary"
        app:floatingLabel="highlight"
        app:primaryColor="?colorAccent"
        app:singleLineEllipsis="true"
        app:helperText="Integer"/>
```
when ```app:helperText="Integer"``` is not there, everything work fine.
I'm on Android 5.0.2.

Stack:
```java
java.lang.RuntimeException: Unable to start activity ComponentInfo{org.antczak.whereIsMyPackage/org.antczak.whereIsMyPackage.activity.AddActivity}: java.lang.IllegalArgumentException: Layout: -64 < 0
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2298)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2360)
            at android.app.ActivityThread.access$800(ActivityThread.java:144)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1278)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5223)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:898)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:693)
     Caused by: java.lang.IllegalArgumentException: Layout: -64 < 0
            at android.text.Layout.<init>(Layout.java:139)
            at android.text.StaticLayout.<init>(StaticLayout.java:105)
            at android.text.StaticLayout.<init>(StaticLayout.java:91)
            at android.text.StaticLayout.<init>(StaticLayout.java:69)
            at android.text.StaticLayout.<init>(StaticLayout.java:49)
            at com.rengwuxian.materialedittext.MaterialEditText.adjustBottomLines(MaterialEditText.java:637)
            at com.rengwuxian.materialedittext.MaterialEditText.setError(MaterialEditText.java:846)
            at com.rengwuxian.materialedittext.MaterialEditText$1.afterTextChanged(MaterialEditText.java:396)
            at android.widget.TextView.sendAfterTextChanged(TextView.java:7679)
            at android.widget.TextView.setText(TextView.java:4056)
            at android.widget.TextView.setText(TextView.java:3905)
            at android.widget.EditText.setText(EditText.java:85)
            at android.widget.TextView.setText(TextView.java:3880)
            at org.antczak.whereIsMyPackage.fragment.AddFragment.onCreateView(AddFragment.java:72)
            at android.support.v4.app.Fragment.performCreateView(Fragment.java:1786)
            at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:947)
            at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1126)
            at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:739)
            at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1489)
            at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:548)
            at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1220)
            at android.app.Activity.performStart(Activity.java:5949)
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2261)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2360)
            at android.app.ActivityThread.access$800(ActivityThread.java:144)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1278)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5223)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:898)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:693)
```

**Comment by danhawkes** [comment] 2015-01-15 14:19
Think this is a dupe of #53.

**Comment by rengwuxian** [comment] 2015-01-17 19:08
1.8.2 has been released, with this fixed. Thanks to @danhawkes 

You can check the [latest library version](https://github.com/rengwuxian/MaterialEditText#download) now. 

_It may take several hours syncing to Maven Central._

**Closed** 2015-01-19 22:17 UTC
Labels: bug, duplicate
